'use client';

import React, { useState } from 'react';
import { ProjectFile } from '@/lib/types';
import { Folder, FolderOpen, FileCode, FileText, Database, Shield } from 'lucide-react';

interface FileTreeProps {
  files: ProjectFile[];
  selectedPath: string;
  onSelect: (path: string) => void;
}

interface TreeNode {
  name: string;
  path: string;
  isFile: boolean;
  file?: ProjectFile;
  children: Record<string, TreeNode>;
}

export function FileTree({ files, selectedPath, onSelect }: FileTreeProps) {
  const [openFolders, setOpenFolders] = useState<Record<string, boolean>>({ '': true });

  // Build tree from paths
  const root: TreeNode = { name: 'root', path: '', isFile: false, children: {} };
  for (const file of files) {
    const parts = file.path.split('/');
    let current = root;
    let currentPath = '';

    parts.forEach((part, index) => {
      currentPath = currentPath ? `${currentPath}/${part}` : part;
      const isLast = index === parts.length - 1;

      if (!current.children[part]) {
        current.children[part] = {
          name: part,
          path: currentPath,
          isFile: isLast,
          file: isLast ? file : undefined,
          children: {},
        };
      }
      current = current.children[part];
    });
  }

  const toggleFolder = (path: string) => {
    setOpenFolders((prev) => ({ ...prev, [path]: !prev[path] }));
  };

  const getFileIcon = (fileName: string) => {
    if (fileName.endsWith('.sql')) return <Database className="w-4 h-4 text-forge-indigo" />;
    if (fileName.includes('auth') || fileName.includes('rls'))
      return <Shield className="w-4 h-4 text-forge-teal" />;
    if (fileName.endsWith('.json') || fileName.endsWith('.md'))
      return <FileText className="w-4 h-4 text-ink-soft" />;
    return <FileCode className="w-4 h-4 text-forge-amber" />;
  };

  const renderNode = (node: TreeNode, depth: number = 0) => {
    const isFolder = !node.isFile;
    const isOpen = openFolders[node.path] ?? true;
    const isSelected = selectedPath === node.path;

    return (
      <div key={node.path} style={{ paddingLeft: `${depth * 12}px` }}>
        {isFolder ? (
          <div>
            <button
              onClick={() => toggleFolder(node.path)}
              className="flex items-center gap-1.5 w-full py-1 px-1.5 rounded text-xs font-mono text-ink hover:bg-ink/5 transition-colors text-left"
            >
              {isOpen ? (
                <FolderOpen className="w-3.5 h-3.5 text-ink-soft" />
              ) : (
                <Folder className="w-3.5 h-3.5 text-ink-soft" />
              )}
              <span className="font-semibold">{node.name}</span>
            </button>
            {isOpen && (
              <div>
                {Object.values(node.children).map((child) => renderNode(child, depth + 1))}
              </div>
            )}
          </div>
        ) : (
          <button
            onClick={() => onSelect(node.path)}
            className={`flex items-center justify-between w-full py-1.5 px-2 rounded text-xs font-mono transition-all text-left group ${
              isSelected
                ? 'bg-ink text-white font-medium shadow-sm'
                : 'text-ink-soft hover:bg-ink/5 hover:text-ink'
            }`}
          >
            <div className="flex items-center gap-1.5 truncate">
              {getFileIcon(node.name)}
              <span className="truncate">{node.name}</span>
            </div>
            {node.file && (
              <span
                title={`Generated by ${node.file.generated_by_model}`}
                className={`w-2 h-2 rounded-full opacity-60 group-hover:opacity-100 shrink-0 ${
                  node.file.generated_by_model.includes('haiku') ||
                  node.file.generated_by_model.includes('flash') ||
                  node.file.generated_by_model.includes('mini')
                    ? 'bg-forge-amber'
                    : 'bg-forge-indigo'
                }`}
              />
            )}
          </button>
        )}
      </div>
    );
  };

  return (
    <div className="w-full h-full bg-white rounded-xl p-3 border border-ink/10 flex flex-col">
      <div className="pb-2 mb-2 border-b border-ink/10 flex items-center justify-between">
        <h5 className="font-display font-bold text-xs uppercase tracking-wider text-ink-soft">
          Generated Files ({files.length})
        </h5>
      </div>
      <div className="flex-1 overflow-y-auto space-y-0.5">
        {files.length === 0 ? (
          <p className="text-xs text-ink-muted p-2 font-mono">No files generated yet</p>
        ) : (
          Object.values(root.children).map((child) => renderNode(child, 0))
        )}
      </div>
    </div>
  );
}
